# Generated by Django 5.0.14 on 2025-10-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairingcode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
