# Generated by Django 5.0.14 on 2025-10-05 20:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MealTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_carbs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('daily_fat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_target', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
