# Generated by Django 5.0.14 on 2025-10-22 17:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealLogging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('glasses', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_ml', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('glass_size', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'water_intake',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='water_intak_user_id_3475ab_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
