# Generated by Django 5.0.14 on 2025-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_goal_alter_profile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'sedentary'), ('light', 'light'), ('moderate', 'moderate'), ('very', 'very'), ('extra', 'extra')], max_length=10, null=True),
        ),
    ]
