# Generated by Django 5.0.14 on 2025-10-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
