# Generated by Django 5.0.14 on 2025-10-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_age_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_years',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
