# Generated by Django 5.0.14 on 2025-10-16 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_age_years_profile_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmr', models.PositiveIntegerField()),
                ('tdee', models.PositiveIntegerField()),
                ('target_calories', models.PositiveIntegerField()),
                ('protein_g', models.PositiveIntegerField()),
                ('fat_g', models.PositiveIntegerField()),
                ('carbs_g', models.PositiveIntegerField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
