# Generated by Django 5.0.14 on 2025-11-11 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_nutritionsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionsnapshot',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
