# Generated by Django 5.0.14 on 2025-10-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
