# Generated by Django 5.0.14 on 2025-10-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
