# Generated by Django 5.0.14 on 2025-11-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_userworkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='met_value',
            field=models.FloatField(default=5.0, help_text='Metabolic Equivalent of Task (MET) - energy expenditure rate'),
        ),
        migrations.AddField(
            model_name='userworkout',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='Estimated calories burned (auto-calculated from profile)', null=True),
        ),
        migrations.AddField(
            model_name='userworkout',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkout',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Workout duration in minutes', null=True),
        ),
    ]
