# Generated by Django 5.0.14 on 2025-11-17 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_exercise_met_value_userworkout_calories_burned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkout',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Workout duration in minutes (minimum 1 minute)', null=True, validators=[django.core.validators.MinValueValidator(1, message='Duration must be at least 1 minute')]),
        ),
    ]
